### ISSUE TITLE
json vs. html

### ISSUE THREAD

**Issue by teuben** [kyleaoman/martini#1]
it seems your ipynb notebook was accidentally stored in html format.

**Comment by kyleaoman** [comment]
I've updated the examples page. Note that github handles *.ipynb files a bit strangely, it's resistant to actually showing the notebook or json directly, and apparently also suffers from some bugs. I've added a readme pointing to a web viewer. The actual notebook can be accessed as normal from a cloned/downloaded copy of the repository.
