### ISSUE TITLE
PyOpenSci: Installation instructions fail on zsh

### ISSUE THREAD

**Issue by taldcroft** [kyleaoman/martini#56]
**Describe the bug**
The installation instructions include directives like `python3 -m pip install astromartini[hdf5_output]`. On `zsh` this fails:
```
zsh: no matches found: astromartini[hdf5_output]
```

**Expected behaviour**
Installation instructions should work with copy/paste for common shells.

**Additional context**
https://github.com/pyOpenSci/software-submission/issues/164

**Comment by kyleaoman** [comment]
Fixed with 39d3fa76defee4609c24b921ae524d18af3a587e
