### ISSUE TITLE
URL doesn't exist: https://github.com/kyleaoman/martini/tree/2.0.X.

### ISSUE THREAD

**Issue by taldcroft** [kyleaoman/martini#57]
The README file provides a link https://github.com/kyleaoman/martini/tree/2.0.X which does not exist.

**Additional context**
https://github.com/pyOpenSci/software-submission/issues/164

**Comment by kyleaoman** [comment]
Corrected with e52a1cf3b82616a53174edab30cef53be23e28b0

@taldcroft since this is a review, would you rather close your own issues, or should I close them (and you can re-open if you feel there's still an issue)?

**Comment by kyleaoman** [comment]
Closing for consistency with automatic closing of issues with linked PRs.
