### ISSUE TITLE
PyOpenSci: http://icc.dur.ac.uk/Eagle/database.php link (in examples/martini_eagle.ipynb) fails to load

### ISSUE THREAD

**Issue by taldcroft** [kyleaoman/martini#58]
**Describe the bug**

The link to get an eagle account http://icc.dur.ac.uk/Eagle/database.php link (in `examples/martini_eagle.ipynb`) fails to load and just hangs.

**Expected behaviour**
Getting an account should be possible via the link.

**Additional context**
https://github.com/pyOpenSci/software-submission/issues/164

**Comment by kyleaoman** [comment]
icc.dur.ac.uk is down right now - there's currently a perfect storm of power system upgrades and end-of-life operating system replacements going on locally. I'll leave this open for now as a reminder to check that access is restored eventually but pretty sure this one is transient and out of my control.

**Comment by kyleaoman** [comment]
Was indeed just a transient service interruption, back to normal now.
