### ISSUE TITLE
Problem with the IllustrisTNG example

### ISSUE THREAD

**Issue by Martindelosrios** [kyleaoman/martini#6]
I am trying to run the Illustris TNG example in the Illustris server, but I found the following error:

from martini import tngdemo; tngdemo()

AttributeError                            Traceback (most recent call last)
<ipython-input-2-cc927d7f8118> in <module>
----> 1 from martini import tngdemo; tngdemo()

/opt/conda/lib/python3.6/site-packages/martini/_tngdemo.py in tngdemo(cubefile, beamfile, hdf5file)
    123     # pixel scale) and consulting the documentation of the sph_kernels sub-
    124     # module to select an appropriate kernel.
--> 125     sph_kernel = GaussianKernel.mimic(
    126         CubicSplineKernel(rescale_sph_h=.5),
    127         truncate=3

AttributeError: type object 'GaussianKernel' has no attribute 'mimic'****

Thanks for your help!

**Comment by kyleaoman** [comment]
The example loaded in new environments on the TNG Jupyterlab got a bit out of date, and I didn't have control of the file to change it. In the future new environments will come with a short readme and instructions to find the up-to-date example. You can find the up-to-date example in the examples directory on github (https://github.com/kyleaoman/martini/tree/master/examples). It's also included in the package in the examples directory, if you get the latest version (for now, of the master branch, and in future numbered branches). If you can check that it works for you before I close the issue that'd be great.

**Comment by Martindelosrios** [comment]
> The example loaded in new environments on the TNG Jupyterlab got a bit out of date, and I didn't have control of the file to change it. In the future new environments will come with a short readme and instructions to find the up-to-date example. You can find the up-to-date example in the examples directory on github (https://github.com/kyleaoman/martini/tree/master/examples). It's also included in the package in the examples directory, if you get the latest version (for now, of the master branch, and in future numbered branches). If you can check that it works for you before I close the issue that'd be great.

Now is working! Thank you very much!

**Comment by kyleaoman** [comment]
Great, thanks. And sorry it took a little while to get back to you.
