### ISSUE TITLE
A question about the final image location

### ISSUE THREAD

**Issue by z20230220** [kyleaoman/martini#73]
Today I creat a toy particle distribution:

**N_points = 10000
x = np.random.uniform(-500, 500, N_points)
y = np.random.uniform(0, 200, N_points)
z = np.random.uniform(20, 200, N_points)**

I plot a projection figure of density distribution in z-y plane as follow:
(I choose "z" as abscissa and "y" as ordinate just because the line of sight is along the positive direction of the x-axis, i.e. the direction perpendicular to the screen, pointing towards the interior of the screen. This arrangement satisfies the cross product rule of coordinates.)

<img src="https://github.com/kyleaoman/martini/assets/125883770/a4c2e099-ba0b-40cf-9be3-d3ab7cd522e9" width="400" height="330" style="margin-right: 10px;">

Then I use MARTINI to produce FluxCube, and calculate the mom0:

**mom0 = np.sum(FluxCube, axis=-1)**

The two images below show: 
Left image: The direct/original mom0
Right image: The mom0 after row-flipping:    **np.flip(mom0, axis=0)**

<img src="https://github.com/kyleaoman/martini/assets/125883770/cdb17fcf-172f-4011-bf6b-0e76cbede4e4" width="1000" height="330" style="margin-right: 10px;">

I've noticed that the direct/original mom0 (left image) has a different position compared to the previous density projection image, while the row-flipped mom0 (right image) is located in the upper-right area, just like the density projection image. 

https://martini.readthedocs.io/en/latest/sources/index.html:
_"A particle at y=0 will be placed at the nominal right ascension of the source (see below), and a particle at z=0 at its nominal declination."_
https://martini.readthedocs.io/en/latest/datacube/index.html:
_"It is recommended to choose even numbers of pixels along each axis for n_px_x (RA axis) and n_px_y (Dec axis)."_

Therefore, I think I should not have misunderstood the meaning of the n_px_x and n_px_y coordinates of the mom0 in the images above. This result is quite confusing to me.

**Comment by kyleaoman** [comment]
The directions along the array axes of the cube are not necessarily intuitive. The RA axis (y axis, ordinate in your figures) in particular follows the usual convention in FITS images where increasing index (pixel number) corresponds to decreasing RA. I think that this is probably the root of your confusion. Also keep in mind that it's conventional to plot RA on the abscissa increasing from right to left, would suggest making your plot that way around. If you're using the FITS output mode of Martini the header will contain the usual information mapping pixels to sky coordinates. (CDELT, CRVAL, etc. for each axis). If using the HDF5 output mode the same is available in the FluxCube attributes, or perhaps more conveniently the RA and Dec datasets contain arrays with the same shape as the FluxCube with the coordinates in each pixel. 

If that doesn't clear up your confusion, let me know.

**Comment by z20230220** [comment]
> The directions along the array axes of the cube are not necessarily intuitive. **The RA axis (y axis, ordinate in your figures)** in particular follows the usual convention in FITS images where increasing index (pixel number) corresponds to decreasing RA...

https://martini.readthedocs.io/en/latest/sources/index.html:
_"A particle at y=0 will be placed at the nominal right ascension of the source (see below), and a particle at z=0 at its nominal declination."_
The "y=0" mentioned in the sentence above should refer to the z-axis (or the x-z plane), so the z-axis of the particle coordinates should actually be parallel to the RA axis. So I think the ordinate in my figure should be the DEC. I hope I shouldn't have confused something...

**Comment by kyleaoman** [comment]
Ah ok, well spotted, that line of the documentation has it backwards. y corresponds to RA, and z corresponds to Dec.

**Comment by kyleaoman** [comment]
I've updated the documentation accordingly, thanks for catching that!

**Comment by z20230220** [comment]
Thanks for your reply. Now the output image is:

<img src="https://github.com/kyleaoman/martini/assets/125883770/e3c5a64e-458d-46e7-a25b-c7f734a503d8" width="400" height="330" style="margin-right: 10px;">

But I think there are still two oddities:
1. The x axis of coordinate system in this figure is opposite to the line of sight. The line of sight should perpendicular to the screen, pointing towards the interior of the screen, but according to cross product rule(or right hand rule): $\vec{e}_{x}=\vec{e}_{y} \times \vec{e}_{z}$, the direction of  x axis is pointing towards the exterior of the screen.

2. When I generate the toy data, the long side of the rectangle should be parallel to the y-axis, but MARTINI's final image shows the long side of the rectangle parallel to the z-axis.

<img src="https://github.com/kyleaoman/martini/assets/125883770/1f21ab4b-88b2-4bff-9f61-86b10948c54b" width="400" height="330" style="margin-right: 10px;">

**Comment by z20230220** [comment]
This is my Python-code, it's simple:

import numpy as np
import random  
import scipy.optimize
import astropy.units as U
import astropy.constants as C
import matplotlib.pyplot as plt
import matplotlib as mpl
import h5py
from martini.sources import SPHSource
from martini import DataCube, Martini
from martini.beams import GaussianBeam
from martini.noise import GaussianNoise
from martini.spectral_models import GaussianSpectrum, DiracDeltaSpectrum
from martini.sph_kernels import CubicSplineKernel, _CubicSplineKernel, find_fwhm

N_points = 10000
x = np.random.uniform(-500, 500, N_points)
y = np.random.uniform(0, 200, N_points)
z = np.random.uniform(20, 200, N_points)
vx = np.zeros(N_points)
vy = np.zeros(N_points)
vz = np.zeros(N_points)
M_gas = 2e+06 * np.ones(N_points)
T = 5e+04 * np.ones(N_points)
M_HI = 4e+05 * np.ones(N_points)
hsm_g = 0.5 * np.ones(N_points)

#pos(3,N)kpc, vel(3,N)km/s, M_gas(1,N)Msol, T(1,N)K, M_HI(1,N)Msol, hsm_g(1,N)kpc
data = np.vstack((x, y, z, vx, vy, vz, M_gas, T, M_HI, hsm_g))
print(data.shape)

plt.figure(figsize=(14, 4))
plt.subplot(1, 2, 1)
plt.hist2d(data[2,:], data[1,:], weights = data[8,:], bins= 500, norm= mpl.colors.LogNorm())
plt.title('Gas Distribution')
plt.colorbar()
plt.gca().set_aspect('equal')
plt.xlim(-50, 50)
plt.ylim(-50, 50)
plt.xlabel('z/kpc')
plt.ylabel('y/kpc')

x_obs = -1000 #kpc
h = 0.6774

source = SPHSource(
    distance=-x_obs * U.kpc,
    #rotation={"L_coords": (60.0 * U.deg, 0.0 * U.deg)},
    ra=0.0 * U.deg,
    dec=0.0 * U.deg,
    h=h,
    T_g=data[7, :] * U.K,
    mHI_g=data[8, :] * U.Msun,
    xyz_g=data[0:3, :] * U.kpc,
    vxyz_g=data[3:6, :] * U.km / U.s,
    hsm_g=data[9, :] * U.kpc,
)

datacube = DataCube(
    n_px_x=300,
    n_px_y=300,
    n_channels=50,
    px_size=60.0 * U.arcsec,
    channel_width=10.0 * U.km * U.s**-1,
    velocity_centre=0 * U.km * U.s**-1, #source.vsys,
    ra=source.ra,
    dec=source.dec,
)

beam = GaussianBeam(
    bmaj=30.0 * U.arcsec, bmin=30.0 * U.arcsec, bpa=0.0 * U.deg, truncate=4.0
)

#noise = GaussianNoise(rms=3.0e-8 * U.Jy * U.beam**-1,seed=0)
noise = GaussianNoise(rms= 0 * U.Jy * U.beam**-1,seed=0)

#spectral_model = DiracDeltaSpectrum()
spectral_model = GaussianSpectrum(sigma="thermal")
#spectral_model = GaussianSpectrum(sigma=7 * U.km * U.s**-1)

sph_kernel = CubicSplineKernel()

M = Martini(
    source=source,
    datacube=datacube,
    beam=beam,
    noise=noise,
    spectral_model=spectral_model,
    sph_kernel=sph_kernel,
)

M.insert_source_in_cube()

M.add_noise()
M.convolve_beam()
M.write_beam_fits("data/local_HIdata/beam_origin.fits", channels="velocity")
M.write_fits("data/local_HIdata/cube_origin.fits", channels="velocity")
M.write_hdf5("data/local_HIdata/cube_origin.hdf5", channels="velocity")

File = h5py.File("data/local_HIdata/cube_origin.hdf5", "r")
print(list(File.keys()))
FluxCube_origin = File["FluxCube"][()]
vch_origin = File["channel_mids"][()] / 1e3 # m/s to km/s
File.close()
FluxCube_origin.shape

np.seterr(all="ignore")
fig = plt.figure(figsize=(17, 5))
sp1 = fig.add_subplot(1, 3, 1)
sp2 = fig.add_subplot(1, 3, 2)

rms_origin = np.std(FluxCube_origin[:16, :16])  # noise in a corner patch where there is little signal
clip_origin = np.where(FluxCube_origin > 5 * rms_origin, 1, 0)
mom0_origin = np.sum(FluxCube_origin, axis=-1)

mask_origin = np.where(mom0_origin > 0.001, 1, np.nan)
mom1_origin = np.sum(FluxCube_origin * clip_origin * vch_origin, axis=-1) / mom0_origin

im1 = sp1.imshow(mom0_origin, cmap="Greys", aspect=1.0, origin="lower", vmax=0.01)
plt.colorbar(im1, ax=sp1, label="mom0 [Jy/beam]")
im2 = sp2.imshow(np.flip(mom0_origin, axis=0), cmap="Greys", aspect=1.0, origin="lower", vmax=0.01)
plt.colorbar(im2, ax=sp2, label="mom0(rows flip) [Jy/beam]")

for sp in sp1, sp2:
    sp.set_xlabel("y(-RA) [px = arcsec/10]")
    sp.set_ylabel("z(+DEC) [px = arcsec/10]")
plt.subplots_adjust(wspace=0.4)
plt.show()

**Comment by z20230220** [comment]
Furthermore, I found this code which is about TNGSource. Before ploting the image, the code transposes the FluxCube/mom0... I guess maybe I need to transpose my cube too?

https://nbviewer.org/github/kyleaoman/martini/blob/main/examples/martini_TNG.ipynb

fig = plt.figure(figsize=(5, 5))
ax = fig.add_subplot(1, 1, 1)

**plt.imshow(FluxCube[:, :, 15].T, cmap="Greys", aspect=1.0, origin="lower")**
ax.autoscale(False)
ax.set_xlabel("x [px = arcsec/{:.0f}]".format(datacube.px_size.to(U.arcsec).value))
ax.set_ylabel("y [px = arcsec/{:.0f}]".format(datacube.px_size.to(U.arcsec).value))
plt.colorbar(label="Flux [Jy/beam]");

**Comment by kyleaoman** [comment]
Here's a schematic of the correspondence between (x, y), (RA, Dec) and pixel indices in the mom0 map (cube summed over spectral axis).
![radec](https://github.com/kyleaoman/martini/assets/32932511/d4132dad-f445-4c46-bead-240fd101fc83)

The right panel is just the left rotated by 90 degrees, and is the conventional way to plot an image with RA and Dec axes. I've checked the martini output carefully and the cube is correct in both the FITS and HDF5 format outputs. `plt.imshow` is notoriously confusing to use, the examples do show (one possible) correct usage with `plt.imshow(mom0.T, origin="lower")`, so yes, you're missing a transpose.

As you've discovered, using `imshow` is not a very intuitive way to visualise the data and makes it hard to be certain that what you're doing is "correct". This is what the "RA" and "Dec" datasets in the HDF5 file are supposed to be for. In checking things over for you I realised two things, however. First, currently only the pixel centres are given. It would make sense to also provide vertices to make it easy to use `plt.pcolormesh` or similar. I'll add that. Second, there's currently a bug in the "RA" and "Dec" datasets due to the default axis ordering of `np.meshgrid` being the opposite of what I always seem to think it should be (see "xy" vs "ij" in https://numpy.org/doc/stable/reference/generated/numpy.meshgrid.html).

I'll fix that bug, add pixel vertices in the output and update the examples to use `pcolormesh` instead of `imshow`. That'll appear as v2.1.3 soon.

**Comment by z20230220** [comment]
Thank you very much for your detailed explanations! I have one more small question, I don't know how to use "RA" and "Dec" in HDF5 data to plot the final image, although I can read the "RA" and "Dec" in HDF5 data. Can you give a simple code example?

I'm looking forward to the next version of MARTINI！

**Comment by kyleaoman** [comment]
That's also included in the new release, see https://martini.readthedocs.io/en/latest/hdf5_output_tips/index.html, and also the tng, eagle and simba example notebooks. 

Note that you'll need to update to 2.1.3 to follow the example code.
